title: Housing Finders
description: <a href="https://house-finders.vercel.app/">A link to our web application</a>
google_analytics:
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
