title: Housing Finders
description: A <a href="https://house-finders.vercel.app/">link</a> to our web application
google_analytics:
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
